/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.UI;

import com.DAO.KhuyenMaiDAO;
import com.Entity.KhuyenMai;
import com.utils.MsgBox;
import java.awt.Color;
import java.awt.Font;
import java.util.Date;
import java.util.List;
import javax.swing.table.JTableHeader;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class KhuyenMaiUI extends javax.swing.JFrame {

    private String MaKM;

    /**
     * Creates new form KhuyenMia
     */
    public KhuyenMaiUI() {
        initComponents();
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new com.k33ptoo.components.KGradientPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtngayKetThuc1 = new com.toedter.calendar.JDateChooser();
        txtngayBD1 = new com.toedter.calendar.JDateChooser();
        txt_MaKM = new javax.swing.JTextField();
        txt_TenKM = new javax.swing.JTextField();
        txt_NoiDung = new javax.swing.JTextField();
        btn_Them = new com.k33ptoo.components.KButton();
        btn_Xoa = new com.k33ptoo.components.KButton();
        btn_Sua = new com.k33ptoo.components.KButton();
        btn_New = new com.k33ptoo.components.KButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_khuyenMai = new javax.swing.JTable();
        lblKetThuc = new javax.swing.JLabel();
        lblThuLai = new javax.swing.JLabel();
        txtgiamGia = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Khuyến Mãi");
        setUndecorated(true);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Mã KM:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Tên KM:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Nội Dung KM:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Ngày BĐ:");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Phần Trăm KM");

        txtngayKetThuc1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        txtngayBD1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        txt_MaKM.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txt_MaKM.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_MaKMFocusLost(evt);
            }
        });

        txt_TenKM.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txt_TenKM.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_TenKMFocusLost(evt);
            }
        });
        txt_TenKM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_TenKMActionPerformed(evt);
            }
        });

        txt_NoiDung.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        btn_Them.setText("Thêm");
        btn_Them.setkEndColor(new java.awt.Color(255, 255, 255));
        btn_Them.setkHoverStartColor(new java.awt.Color(153, 255, 153));
        btn_Them.setkSelectedColor(new java.awt.Color(153, 0, 153));
        btn_Them.setkStartColor(new java.awt.Color(0, 153, 255));
        btn_Them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ThemActionPerformed(evt);
            }
        });

        btn_Xoa.setText("Xóa");
        btn_Xoa.setkEndColor(new java.awt.Color(255, 255, 255));
        btn_Xoa.setkHoverStartColor(new java.awt.Color(153, 255, 153));
        btn_Xoa.setkSelectedColor(new java.awt.Color(153, 0, 153));
        btn_Xoa.setkStartColor(new java.awt.Color(0, 153, 255));
        btn_Xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_XoaActionPerformed(evt);
            }
        });

        btn_Sua.setText("Sửa");
        btn_Sua.setkEndColor(new java.awt.Color(255, 255, 255));
        btn_Sua.setkHoverStartColor(new java.awt.Color(153, 255, 153));
        btn_Sua.setkSelectedColor(new java.awt.Color(153, 0, 153));
        btn_Sua.setkStartColor(new java.awt.Color(0, 153, 255));
        btn_Sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SuaActionPerformed(evt);
            }
        });

        btn_New.setText("Mới");
        btn_New.setkEndColor(new java.awt.Color(255, 255, 255));
        btn_New.setkHoverStartColor(new java.awt.Color(153, 255, 153));
        btn_New.setkSelectedColor(new java.awt.Color(153, 0, 153));
        btn_New.setkStartColor(new java.awt.Color(0, 153, 255));
        btn_New.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_NewActionPerformed(evt);
            }
        });

        tbl_khuyenMai.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã KM", "Tên KM", "Nôi Dung", "Ngày BĐ", "Ngày KT", "Phần Trăm Giảm"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tbl_khuyenMai.setGridColor(new java.awt.Color(255, 255, 255));
        tbl_khuyenMai.setSelectionBackground(new java.awt.Color(0, 158, 250));
        tbl_khuyenMai.setShowHorizontalLines(false);
        tbl_khuyenMai.setShowVerticalLines(false);
        jScrollPane2.setViewportView(tbl_khuyenMai);

        lblKetThuc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblKetThuc.setIcon(new ImageIcon( getClass().getClassLoader().getResource("Images/close_1.png"))
        );
        lblKetThuc.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblKetThuc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblKetThucMouseClicked(evt);
            }
        });

        lblThuLai.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblThuLai.setIcon(new ImageIcon( getClass().getClassLoader().getResource("Images/minus.png"))
        );
        lblThuLai.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblThuLai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblThuLaiMouseClicked(evt);
            }
        });

        txtgiamGia.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtgiamGiaFocusLost(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Ngày KT:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Khuyến Mãi");

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_TenKM, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_MaKM, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_NoiDung, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtgiamGia, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtngayBD1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtngayKetThuc1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(btn_Them, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_Xoa, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_Sua, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_New, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(255, 255, 255)
                .addComponent(lblThuLai, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblKetThuc, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 819, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        kGradientPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel10, jLabel4, jLabel7, jLabel8, jLabel9});

        kGradientPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txt_MaKM, txt_NoiDung, txt_TenKM, txtgiamGia, txtngayBD1, txtngayKetThuc1});

        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lblKetThuc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblThuLai, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)))
                .addGap(25, 25, 25)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                .addComponent(txt_MaKM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txt_TenKM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(16, 16, 16)
                                .addComponent(txt_NoiDung, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel7)
                                .addGap(22, 22, 22)
                                .addComponent(jLabel8)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel11))
                            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                .addComponent(txtngayBD1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtngayKetThuc1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtgiamGia, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_Them, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_Xoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_Sua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_New, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );

        kGradientPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel10, jLabel4, jLabel7, jLabel8, jLabel9});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_TenKMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_TenKMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_TenKMActionPerformed

    private void lblKetThucMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblKetThucMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_lblKetThucMouseClicked

    private void lblThuLaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblThuLaiMouseClicked
        // TODO add your handling code here:
        this.setState(KhuyenMaiUI.ICONIFIED);
    }//GEN-LAST:event_lblThuLaiMouseClicked

    private void btn_ThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ThemActionPerformed
        insert();
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_ThemActionPerformed

    private void btn_XoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_XoaActionPerformed
        delete();
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_XoaActionPerformed

    private void btn_SuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SuaActionPerformed
        update();
// TODO add your handling code here:
    }//GEN-LAST:event_btn_SuaActionPerformed

    private void btn_NewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_NewActionPerformed
        cleanForm();
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_NewActionPerformed

    private void txt_MaKMFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_MaKMFocusLost
       
    }//GEN-LAST:event_txt_MaKMFocusLost

    private void txtgiamGiaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtgiamGiaFocusLost
       


    }//GEN-LAST:event_txtgiamGiaFocusLost

    private void txt_TenKMFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_TenKMFocusLost
        // TODO add your handling code here:
        String tenKM = txt_TenKM.getText();
        if (tenKM.length() > 0) {
        } else {
            JOptionPane.showConfirmDialog(rootPane, "Tên Khuyến Mãi Không Được Để Trống");
        }

    }//GEN-LAST:event_txt_TenKMFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KhuyenMaiUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KhuyenMaiUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KhuyenMaiUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KhuyenMaiUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KhuyenMaiUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.k33ptoo.components.KButton btn_New;
    private com.k33ptoo.components.KButton btn_Sua;
    private com.k33ptoo.components.KButton btn_Them;
    private com.k33ptoo.components.KButton btn_Xoa;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private com.k33ptoo.components.KGradientPanel kGradientPanel1;
    private javax.swing.JLabel lblKetThuc;
    private javax.swing.JLabel lblThuLai;
    private javax.swing.JTable tbl_khuyenMai;
    private javax.swing.JTextField txt_MaKM;
    private javax.swing.JTextField txt_NoiDung;
    private javax.swing.JTextField txt_TenKM;
    private javax.swing.JTextField txtgiamGia;
    private com.toedter.calendar.JDateChooser txtngayBD1;
    private com.toedter.calendar.JDateChooser txtngayKetThuc1;
    // End of variables declaration//GEN-END:variables
  KhuyenMaiDAO dao = new KhuyenMaiDAO();
    int row = -1;

    private void init() {
        this.setLocationRelativeTo(null);
        setTable();
        filltable();
        chon();
    }

    private void setTable() {
        JTableHeader hd2 = tbl_khuyenMai.getTableHeader();
        hd2.setBackground(new Color(0, 102, 255));
        hd2.setForeground(Color.white);
        tbl_khuyenMai.getTableHeader().setFont(new Font("Tahoma", Font.PLAIN, 16));
        tbl_khuyenMai.setShowHorizontalLines(false);
        tbl_khuyenMai.setShowVerticalLines(false);
    }

    void filltable() {
        DefaultTableModel model = (DefaultTableModel) tbl_khuyenMai.getModel();
        model.setRowCount(0);
        try {
            List<KhuyenMai> list = dao.selectAll();
            for (KhuyenMai kM : list) {
                Object[] row = {kM.getMaKM(), kM.getTenKM(), kM.getNoiDung(), kM.getNgayBD(), kM.getNgayKT(), kM.getPhanTramGiam()};
                model.addRow(row);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }

    }
    
    public boolean checkForm(){
        if(txt_MaKM.getText().trim().isEmpty()){
            MsgBox.alert(null,"Không để trống mã khuyến mãi");
            return false;
        }else if(txt_NoiDung.getText().trim().isEmpty()){
             MsgBox.alert(null,"Không để trống nội dung");
            return false;
        }else if(txt_TenKM.getText().trim().isEmpty()){
             MsgBox.alert(null,"Không để trống tên khuyến mãi");
            return false;
        }else if(txtgiamGia.getText().trim().isEmpty()){
             MsgBox.alert(null,"Không để trống giảm giá");
            return false;
        }else if(txtngayBD1.getDate() == null){
             MsgBox.alert(null,"Không để trống ngày bắt đầu");
            return false;
        }else if(txtngayKetThuc1.getDate() == null){
             MsgBox.alert(null,"Không để trống ngày kết thúc");
            return false;
        }
        try{
            float f = Float.parseFloat(txtgiamGia.getText());
        }catch(NumberFormatException e){
            MsgBox.alert(null,"Phần trăm giảm không hợp lệ(không nhập ký tự đặc biệt)");
            return false;
        }
        return true;
    }

    KhuyenMai getForm() {
        KhuyenMai kM = new KhuyenMai();
        kM.setMaKM(txt_MaKM.getText());
        kM.setTenKM(txt_TenKM.getText());
        kM.setNoiDung(txt_NoiDung.getText());
        kM.setNgayBD(txtngayBD1.getDate());
        kM.setNgayKT(txtngayKetThuc1.getDate());
        kM.setPhanTramGiam(Float.parseFloat(txtgiamGia.getText()));
        return kM;
    }

    void setform(KhuyenMai kM) {
        txt_MaKM.setText(kM.getMaKM());
        txt_TenKM.setText(kM.getTenKM());
        txt_NoiDung.setText(kM.getNoiDung());
        txtngayBD1.setDate(txtngayBD1.getDate());
        txtngayKetThuc1.setDate(txtngayKetThuc1.getDate());
        txtgiamGia.setText(String.valueOf(kM.getPhanTramGiam()));
    }

    void insert() {
        if(checkForm() == false)
            return;
        KhuyenMai kM = getForm();
       
            dao.insert(kM);
            this.filltable();
            this.cleanForm();
            MsgBox.alert(null,"Thêm thành công");
        

    }

    void cleanForm() {
        KhuyenMai kM = new KhuyenMai();
        this.setform(kM);
        this.row = 0;
    }

    void update() {
        if(checkForm() == false)
            return;
        KhuyenMai kM = getForm();
        
            dao.update(kM);
            this.filltable();
            this.cleanForm();
            MsgBox.alert(null,"Cập nhật thành công");
        
    }

    void chon() {
        tbl_khuyenMai.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                if (tbl_khuyenMai.getSelectedRow() >= 0) {
                    txt_MaKM.setText(tbl_khuyenMai.getValueAt(tbl_khuyenMai.getSelectedRow(), 0) + "");
                    txt_TenKM.setText(tbl_khuyenMai.getValueAt(tbl_khuyenMai.getSelectedRow(), 1) + "");
                    txt_NoiDung.setText(tbl_khuyenMai.getValueAt(tbl_khuyenMai.getSelectedRow(), 2) + "");
                    txtngayBD1.setDate((Date) tbl_khuyenMai.getValueAt(tbl_khuyenMai.getSelectedRow(), 3));
                    txtngayKetThuc1.setDate((Date) tbl_khuyenMai.getValueAt(tbl_khuyenMai.getSelectedRow(), 4));
                    txtgiamGia.setText(tbl_khuyenMai.getValueAt(tbl_khuyenMai.getSelectedRow(), 5) + "");
                }
            }
        });
    }

    void delete() {
        String maKM = txt_MaKM.getText();
        try {
            dao.delete(maKM);
            this.filltable();
            this.cleanForm();
             MsgBox.alert(null,"Xóa thành công");

        } catch (Exception e) {
            e.printStackTrace();
           
        }

    }
//    void test(){
//        try {
//            if( ){
//            }
//        } catch (Exception e) {
//        }
//    }

}
