/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.UI;

import com.DAO.NhanVienDAO;
import com.Entity.NhanVien;
import com.utils.MsgBox;
import com.utils.XDate;
import java.awt.Color;
import java.awt.Font;
import java.io.File;
import java.time.Instant;
import java.util.Date;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableCellRenderer;

/**
 *
 * @author ASUS
 */
public class QuanLyNhanVien extends javax.swing.JFrame {

    /**
     * Creates new form NhanVien
     */
    public QuanLyNhanVien() {
        initComponents();
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jTextField7 = new javax.swing.JTextField();
        buttonGroup2 = new javax.swing.ButtonGroup();
        kGradientPanel1 = new com.k33ptoo.components.KGradientPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtManv = new javax.swing.JTextField();
        txthoTen = new javax.swing.JTextField();
        txtnamSinh = new com.toedter.calendar.JDateChooser();
        txtdiaChi = new javax.swing.JTextField();
        txtSDT = new javax.swing.JTextField();
        rdoNam = new javax.swing.JRadioButton();
        rdoNu = new javax.swing.JRadioButton();
        txteMail = new javax.swing.JTextField();
        txtmatKhau = new javax.swing.JPasswordField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_NhanVien = new javax.swing.JTable();
        btn_ThemNV = new com.k33ptoo.components.KButton();
        btn_XoaNV2 = new com.k33ptoo.components.KButton();
        btn_SuaNV = new com.k33ptoo.components.KButton();
        btn_New = new com.k33ptoo.components.KButton();
        lblKetThuc1 = new javax.swing.JLabel();
        lblThuLai1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        rdo_NhanVien = new javax.swing.JRadioButton();
        rdo_QuanLy = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        btn_XoaNV = new com.k33ptoo.components.KButton();

        jTextField7.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản Lý Nhân Viên");
        setUndecorated(true);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Mã Nhân Viên:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Họ Tên:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Năm Sinh:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Địa Chỉ:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("SĐT:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Giới Tính:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Email:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Mật Khẩu:");

        txtManv.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtManv.setToolTipText("Nhập mã nhân viên");

        txthoTen.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txthoTen.setToolTipText("Nhập họ và tên");
        txthoTen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txthoTenActionPerformed(evt);
            }
        });

        txtnamSinh.setToolTipText("dd/MM/yy");
        txtnamSinh.setDateFormatString("dd/MM/yyyy");
        txtnamSinh.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        txtdiaChi.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtdiaChi.setToolTipText("Nhập địa chỉ");
        txtdiaChi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdiaChiActionPerformed(evt);
            }
        });

        txtSDT.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtSDT.setToolTipText("Nhập số điện thoại");

        buttonGroup1.add(rdoNam);
        rdoNam.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        rdoNam.setForeground(new java.awt.Color(255, 255, 255));
        rdoNam.setSelected(true);
        rdoNam.setText("Nam");
        rdoNam.setOpaque(false);

        buttonGroup1.add(rdoNu);
        rdoNu.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        rdoNu.setForeground(new java.awt.Color(255, 255, 255));
        rdoNu.setText("Nữ");
        rdoNu.setOpaque(false);

        txteMail.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txteMail.setToolTipText("Nhập email");
        txteMail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txteMailActionPerformed(evt);
            }
        });

        txtmatKhau.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtmatKhau.setToolTipText("Nhập mật khẩu");

        tbl_NhanVien.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        tbl_NhanVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã NV ", "Họ Tên", "Số ĐT", "Địa Chỉ", "Email", "Chức vụ", "Năm sinh", "Mật khẩu", "Giới tính"
            }
        ));
        tbl_NhanVien.setGridColor(new java.awt.Color(255, 255, 255));
        tbl_NhanVien.setRowHeight(25);
        tbl_NhanVien.setSelectionBackground(new java.awt.Color(0, 158, 250));
        tbl_NhanVien.setShowHorizontalLines(false);
        tbl_NhanVien.setShowVerticalLines(false);
        tbl_NhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_NhanVienMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_NhanVien);

        btn_ThemNV.setText("Thêm");
        btn_ThemNV.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btn_ThemNV.setkEndColor(new java.awt.Color(255, 255, 255));
        btn_ThemNV.setkHoverStartColor(new java.awt.Color(0, 204, 204));
        btn_ThemNV.setkStartColor(new java.awt.Color(0, 153, 255));
        btn_ThemNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ThemNVActionPerformed(evt);
            }
        });

        btn_XoaNV2.setText("Tạo QR code");
        btn_XoaNV2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btn_XoaNV2.setkEndColor(new java.awt.Color(255, 255, 255));
        btn_XoaNV2.setkHoverStartColor(new java.awt.Color(0, 204, 204));
        btn_XoaNV2.setkStartColor(new java.awt.Color(0, 153, 255));
        btn_XoaNV2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_XoaNV2ActionPerformed(evt);
            }
        });

        btn_SuaNV.setText("Sửa");
        btn_SuaNV.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btn_SuaNV.setkEndColor(new java.awt.Color(255, 255, 255));
        btn_SuaNV.setkHoverStartColor(new java.awt.Color(0, 204, 204));
        btn_SuaNV.setkStartColor(new java.awt.Color(0, 153, 255));
        btn_SuaNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SuaNVActionPerformed(evt);
            }
        });

        btn_New.setText("Làm mới");
        btn_New.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btn_New.setkEndColor(new java.awt.Color(255, 255, 255));
        btn_New.setkHoverStartColor(new java.awt.Color(0, 204, 204));
        btn_New.setkStartColor(new java.awt.Color(0, 153, 255));
        btn_New.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_NewActionPerformed(evt);
            }
        });

        lblKetThuc1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblKetThuc1.setIcon(new ImageIcon( getClass().getClassLoader().getResource("Images/close_1.png"))
        );
        lblKetThuc1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblKetThuc1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblKetThuc1MouseClicked(evt);
            }
        });

        lblThuLai1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblThuLai1.setIcon(new ImageIcon( getClass().getClassLoader().getResource("Images/minus.png"))
        );
        lblThuLai1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblThuLai1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblThuLai1MouseClicked(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Chức vụ:");

        buttonGroup2.add(rdo_NhanVien);
        rdo_NhanVien.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        rdo_NhanVien.setForeground(new java.awt.Color(255, 255, 255));
        rdo_NhanVien.setSelected(true);
        rdo_NhanVien.setText("Nhân viên");
        rdo_NhanVien.setOpaque(false);

        buttonGroup2.add(rdo_QuanLy);
        rdo_QuanLy.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        rdo_QuanLy.setForeground(new java.awt.Color(255, 255, 255));
        rdo_QuanLy.setText("Quản lý");
        rdo_QuanLy.setOpaque(false);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 28)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Quản Lý Nhân Viên");

        btn_XoaNV.setText("Xóa");
        btn_XoaNV.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btn_XoaNV.setkEndColor(new java.awt.Color(255, 255, 255));
        btn_XoaNV.setkHoverStartColor(new java.awt.Color(0, 204, 204));
        btn_XoaNV.setkStartColor(new java.awt.Color(0, 153, 255));
        btn_XoaNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_XoaNVActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGap(302, 302, 302)
                .addComponent(btn_ThemNV, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(btn_XoaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_SuaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_New, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_XoaNV2, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtmatKhau))
                            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtSDT))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txteMail))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(rdoNam, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(rdoNu, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(rdo_NhanVien)
                                .addGap(34, 34, 34)
                                .addComponent(rdo_QuanLy))
                            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtManv)
                                    .addComponent(txthoTen)
                                    .addComponent(txtdiaChi)
                                    .addComponent(txtnamSinh, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 869, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(382, 382, 382)
                        .addComponent(lblThuLai1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblKetThuc1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1)))
                .addContainerGap())
        );

        kGradientPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel1, jLabel2, jLabel3, jLabel4, jLabel5, jLabel6, jLabel7, jLabel8, jLabel9});

        kGradientPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btn_New, btn_SuaNV, btn_ThemNV, btn_XoaNV2});

        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblKetThuc1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblThuLai1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel10)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtManv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txthoTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(txtnamSinh, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                .addComponent(txtdiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)))
                        .addGap(18, 18, 18)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(rdo_NhanVien)
                            .addComponent(rdo_QuanLy))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(rdoNam)
                            .addComponent(rdoNu))
                        .addGap(28, 28, 28)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txteMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(txtmatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_XoaNV2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_SuaNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_New, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_ThemNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_XoaNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
        );

        kGradientPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel1, jLabel2, jLabel3, jLabel4, jLabel5, jLabel6, jLabel7, jLabel8, jLabel9});

        kGradientPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txtManv, txtSDT, txthoTen});

        kGradientPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btn_New, btn_SuaNV, btn_ThemNV, btn_XoaNV2});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(kGradientPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txteMailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txteMailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txteMailActionPerformed

    private void txtdiaChiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdiaChiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdiaChiActionPerformed

    private void lblKetThuc1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblKetThuc1MouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_lblKetThuc1MouseClicked

    private void lblThuLai1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblThuLai1MouseClicked
        // TODO add your handling code here:
        this.setState(QuanLyNhanVien.ICONIFIED);
    }//GEN-LAST:event_lblThuLai1MouseClicked

    private void btn_NewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_NewActionPerformed
        // TODO add your handling code here:
        settext();
    }//GEN-LAST:event_btn_NewActionPerformed

    private void btn_ThemNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ThemNVActionPerformed
        // TODO add your handling code here:
        this.insert();
    }//GEN-LAST:event_btn_ThemNVActionPerformed
    public String chooseQR() {
        JFileChooser chooser = new JFileChooser();
        if (chooser.showSaveDialog(this) == JFileChooser.APPROVE_OPTION) {
            File file = chooser.getSelectedFile();
            return file.getAbsolutePath();
        }
        return "";
    }
    private void btn_XoaNV2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_XoaNV2ActionPerformed
        if (row == -1) {

        }
        String data = tbl_NhanVien.getValueAt(row, 0).toString();
        try {
            MyQr.createQR(data, chooseQR());
        } catch (Exception e) {
            e.printStackTrace();
        }

        this.delete();
    }//GEN-LAST:event_btn_XoaNV2ActionPerformed

    private void btn_SuaNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SuaNVActionPerformed
        // TODO add your handling code here:
        this.update();
    }//GEN-LAST:event_btn_SuaNVActionPerformed

    private void tbl_NhanVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_NhanVienMouseClicked

        row = tbl_NhanVien.getSelectedRow();
        this.edit();

    }//GEN-LAST:event_tbl_NhanVienMouseClicked

    private void txthoTenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txthoTenActionPerformed

    }//GEN-LAST:event_txthoTenActionPerformed

    private void btn_XoaNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_XoaNVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_XoaNVActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLyNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLyNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLyNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLyNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuanLyNhanVien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.k33ptoo.components.KButton btn_New;
    private com.k33ptoo.components.KButton btn_SuaNV;
    private com.k33ptoo.components.KButton btn_ThemNV;
    private com.k33ptoo.components.KButton btn_XoaNV;
    private com.k33ptoo.components.KButton btn_XoaNV2;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField7;
    private com.k33ptoo.components.KGradientPanel kGradientPanel1;
    private javax.swing.JLabel lblKetThuc1;
    private javax.swing.JLabel lblThuLai1;
    private javax.swing.JRadioButton rdoNam;
    private javax.swing.JRadioButton rdoNu;
    private javax.swing.JRadioButton rdo_NhanVien;
    private javax.swing.JRadioButton rdo_QuanLy;
    private javax.swing.JTable tbl_NhanVien;
    private javax.swing.JTextField txtManv;
    private javax.swing.JTextField txtSDT;
    private javax.swing.JTextField txtdiaChi;
    private javax.swing.JTextField txteMail;
    private javax.swing.JTextField txthoTen;
    private javax.swing.JPasswordField txtmatKhau;
    private com.toedter.calendar.JDateChooser txtnamSinh;
    // End of variables declaration//GEN-END:variables
    private void init() {
        this.setLocationRelativeTo(null);
        setTable();
        fillToTable();
        updateStatus();
    }

    private void setTable() {
        TableCellRenderer rendererFromHeader = tbl_NhanVien.getTableHeader().getDefaultRenderer();/* Căn giữa title ở header of table_KindOfRoom */
        JLabel headerLabel = (JLabel) rendererFromHeader;
        headerLabel.setHorizontalAlignment(JLabel.CENTER);

        JTableHeader hd = tbl_NhanVien.getTableHeader();/* set màu chữ và màu background cho header*/
        hd.setBackground(new Color(0, 102, 255));
        hd.setForeground(Color.BLACK);
        tbl_NhanVien.getTableHeader().setFont(new Font("Tahoma", Font.PLAIN, 16));

        DefaultTableCellRenderer centerTable = new DefaultTableCellRenderer();/* căn giữa text in column */
        centerTable.setHorizontalAlignment(JLabel.CENTER);

        tbl_NhanVien.getColumnModel().getColumn(0).setCellRenderer(centerTable);
        tbl_NhanVien.getColumnModel().getColumn(1).setCellRenderer(centerTable);
        tbl_NhanVien.getColumnModel().getColumn(2).setCellRenderer(centerTable);
        tbl_NhanVien.getColumnModel().getColumn(4).setCellRenderer(centerTable);
        tbl_NhanVien.getColumnModel().getColumn(5).setCellRenderer(centerTable);
        tbl_NhanVien.getColumnModel().getColumn(6).setCellRenderer(centerTable);
        tbl_NhanVien.getColumnModel().getColumn(7).setCellRenderer(centerTable);
        tbl_NhanVien.getColumnModel().getColumn(8).setCellRenderer(centerTable);
    }

    NhanVienDAO dao = new NhanVienDAO();
    int row = -1;

    void fillToTable() {
        DefaultTableModel model = (DefaultTableModel) tbl_NhanVien.getModel();
        model.setRowCount(0);
        try {
            List<NhanVien> list = dao.selectAll();
            for (NhanVien nv : list) {
                model.addRow(new Object[]{
                    nv.getMaNV(),
                    nv.getHoTen(),
                    nv.getSoDT(),
                    nv.getDiaChi(),
                    nv.getEmail(),
                    nv.getChuVu() ? "Quản Lý" : "Nhân Viên",
                    nv.getNamSinh(),
                    nv.getMaKhau(),
                    nv.getGioiTinh() ? "Nam" : "Nữ",});
            }

        } catch (Exception e) {

        }
    }

    private void settext() {
        txtManv.setText("");
        txthoTen.setText("");
        txtSDT.setText("");
        txtdiaChi.setText("");
        txteMail.setText("");
        rdo_NhanVien.setSelected(true);
        rdoNam.setSelected(true);
        txteMail.setText("");
        txtmatKhau.setText("");
        txtnamSinh.setDate(null);
    }

    /* setForm cho Loại phòng */
    public void setForm(NhanVien nv) {
        txtManv.setText(nv.getMaNV());
        txthoTen.setText(nv.getHoTen());
        txtnamSinh.setDate(nv.getNamSinh());
        txtdiaChi.setText(nv.getDiaChi());
        txtSDT.setText(nv.getSoDT());
        rdo_NhanVien.setSelected(nv.getChuVu());
        rdo_QuanLy.setSelected(!nv.getChuVu());
        rdoNam.setSelected(nv.getGioiTinh());
        rdoNu.setSelected(!nv.getGioiTinh());
        txteMail.setText(nv.getEmail());
        txtmatKhau.setText(nv.getMaKhau());
    }

    /* getForm cho Loại phòng */
    public NhanVien getForm() {
        NhanVien nv = new NhanVien();
        nv.setMaNV(txtManv.getText());
        nv.setHoTen(txthoTen.getText());
        nv.setNamSinh(txtnamSinh.getDate());
        nv.setDiaChi(txtdiaChi.getText());
        nv.setSoDT(txtSDT.getText());

        boolean cv;
        if (rdo_NhanVien.isSelected()) {
            cv = true;
        } else {
            cv = false;
        }
        nv.setChuVu(cv);

        boolean gt;
        if (rdoNam.isSelected()) {
            gt = true;
        } else {
            gt = false;
        }
        nv.setGioiTinh(gt);
        nv.setEmail(txteMail.getText());
        nv.setMaKhau(new String(txtmatKhau.getPassword()));

        return nv;
    }

    public void insert() {

        NhanVien nv = getForm();

        if (txtManv.getText().equals("")) {
            MsgBox.warring(this, "Mã nhân viên không được để trống!");
            txtManv.requestFocus();
            txtManv.setBackground(Color.yellow);
            return;
        } else {
            txtManv.setBackground(Color.white);
        }
        if (txthoTen.getText().equals("")) {
            MsgBox.warring(this, "Họ và tên không được để trống!");;
            txthoTen.requestFocus();
            txthoTen.setBackground(Color.yellow);
            return;
        } else {
            txthoTen.setBackground(Color.white);
        }
        if (txtdiaChi.getText().equals("")) {
            MsgBox.warring(this, "Địa chỉ không được để trống!");
            txtdiaChi.requestFocus();
            txtdiaChi.setBackground(Color.yellow);
            return;
        } else {
            txtdiaChi.setBackground(Color.white);
        }
        if (txtSDT.getText().equals("")) {
            MsgBox.warring(this, "Số ĐT không được để trống");
            txtSDT.requestFocus();
            txtSDT.setBackground(Color.yellow);
            return;
        } else {
            txtSDT.setBackground(Color.white);
        }
        String phone = "0\\d{9}";
        if (!txtSDT.getText().matches(phone)) {
            MsgBox.warring(this, "Số ĐT không đúng định dạng");
            txtSDT.requestFocus();
            txtSDT.setBackground(Color.yellow);
            return;
        } else {
            txtSDT.setBackground(Color.white);
        }
        if (txteMail.getText().equals("")) {
            MsgBox.warring(this, "Email không được để trống!");;
            txteMail.requestFocus();
            txteMail.setBackground(Color.yellow);
            return;
        } else {
            txteMail.setBackground(Color.white);
        }
//        st.Email = txtEmail.getText();
        String Email = "\\w+@\\w+(\\.\\w+){1,2}";
        if (!txteMail.getText().matches(Email)) {
            MsgBox.warring(this, "Email không đúng định dạng!");
            txteMail.requestFocus();
            txteMail.setBackground(Color.yellow);
            return;
        } else {
            txteMail.setBackground(Color.white);
        }
        if (txtmatKhau.getText().equals("")) {
            MsgBox.warring(this, "Mật khẩu không được để trống");
            txtmatKhau.requestFocus();
            txtmatKhau.setBackground(Color.yellow);
            return;
        } else {
            txtmatKhau.setBackground(Color.white);

        }

        try {

            dao.insert(nv);
            this.fillToTable();
            this.clearForm();
            MsgBox.alert(this, "Thêm thành công!");
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public void delete() {

        String maNV = txtManv.getText();
        if (MsgBox.confirm(this, "Bạn có chắc muốn xóa ?")) {
            try {
                dao.delete(maNV);
                this.fillToTable();
                this.clearForm();
                settext();
                MsgBox.alert(this, "Xóa thành công!");
                settext();
            } catch (Exception e) {
                e.printStackTrace();
            }
        }

    }

    public void update() {

        NhanVien lp = getForm();

        if (txtManv.getText().equals("")) {
            MsgBox.warring(this, "Mã nhân viên không được để trống!");
            txtManv.requestFocus();
            txtManv.setBackground(Color.yellow);
            return;
        } else {
            txtManv.setBackground(Color.white);
        }
        if (txthoTen.getText().equals("")) {
            MsgBox.warring(this, "Họ và tên không được để trống!");;
            txthoTen.requestFocus();
            txthoTen.setBackground(Color.yellow);
            return;
        } else {
            txthoTen.setBackground(Color.white);
        }
        if (txtdiaChi.getText().equals("")) {
            MsgBox.warring(this, "Địa chỉ không được để trống!");
            txtdiaChi.requestFocus();
            txtdiaChi.setBackground(Color.yellow);
            return;
        } else {
            txtdiaChi.setBackground(Color.white);
        }
        if (txtSDT.getText().equals("")) {
            MsgBox.warring(this, "Số ĐT không được để trống");
            txtSDT.requestFocus();
            txtSDT.setBackground(Color.yellow);
            return;
        } else {
            txtSDT.setBackground(Color.white);
        }
        String phone = "0\\d{9}";
        if (!txtSDT.getText().matches(phone)) {
            MsgBox.warring(this, "Số ĐT không đúng định dạng");
            txtSDT.requestFocus();
            txtSDT.setBackground(Color.yellow);
            return;
        } else {
            txtSDT.setBackground(Color.white);
        }
        if (txteMail.getText().equals("")) {
            MsgBox.warring(this, "Email không được để trống!");;
            txteMail.requestFocus();
            txteMail.setBackground(Color.yellow);
            return;
        } else {
            txteMail.setBackground(Color.white);
        }
//        st.Email = txtEmail.getText();
        String Email = "\\w+@\\w+(\\.\\w+){1,2}";
        if (!txteMail.getText().matches(Email)) {
            MsgBox.warring(this, "Email không đúng định dạng!");
            txteMail.requestFocus();
            txteMail.setBackground(Color.yellow);
            return;
        } else {
            txteMail.setBackground(Color.white);
        }
        if (txtmatKhau.getText().equals("")) {
            MsgBox.warring(this, "Mật khẩu không được để trống");
            txtmatKhau.requestFocus();
            txtmatKhau.setBackground(Color.yellow);
            return;
        } else {
            txtmatKhau.setBackground(Color.white);
        }

        try {
            dao.update(lp);
            this.fillToTable();
            MsgBox.alert(this, "Cập nhật thành công!");
        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    private void edit() {
        String maNV = (String) tbl_NhanVien.getValueAt(this.row, 0);
        NhanVien nv = dao.selectById(maNV);
        this.setForm(nv);
        this.updateStatus();
    }

    public void updateStatus() {
        boolean editRoom = (this.row >= 0);
        boolean firstRoom = (this.row == 0);
        boolean lastRoom = (this.row == tbl_NhanVien.getRowCount() - 1);

        btn_ThemNV.setEnabled(editRoom);
        btn_SuaNV.setEnabled(editRoom);
        btn_XoaNV2.setEnabled(editRoom);

    }

    public void first() {
        this.row = 0;
        this.edit();
    }

    public void prev() {
        if (this.row > 0) {
            this.row--;
            this.edit();
        }
    }

    public void next() {
        if (this.row < tbl_NhanVien.getRowCount() - 1) {
            this.row++;
            this.edit();
        }
    }

    public void last() {
        this.row = tbl_NhanVien.getRowCount() - 1;
        this.edit();
    }

    private void clearForm() {
        NhanVien nv = new NhanVien();
        settext();
        this.row = -1;
        this.updateStatus();
    }

}
